# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = ENV['4d8e04dee6c4bbbc72d310f24f6c6c02']
  config.secret_key = ENV['8c1c19036312572005df63d23dc35abf']
  config.default_from = 'lion.d.dev+thp@gmail.com'

end
