# kindly generated by appropriated Rails generator
require 'dotenv'
Dotenv.load

Mailjet.configure do |config|
  config.api_key = ENV['MAILJET_API_KEY']
  config.secret_key = ENV['MAILJET_SECRET_KEY']
  config.default_from = 'lion.d.dev+thp@gmail.com'
end
